export const iconNames = [
  'back-button',
  'badge-check-2',
  'badge-check',
  'favorite-button-whitout-prototype',
  'filter-list',
  'more',
  'search-alt',
  'triangle-exclamation',
  'message-circle-lines',
  'plus',
  'shapes',
  'user-alt-1',
  'users-alt-2',
  'eye-slash-icon',
  'eye-icon',
  'arrow-right-to-bracket',
  'x-mark',
  'key-alt',
  'mail-alt-3',
] as const;
